---
# yamllint disable rule:line-length
name: renovate

on:
  schedule:
  - cron: '0 4 * * *'
  pull_request:
    paths:
    - '.github/workflows/renovate.yaml'
    - '.github/renovate.json'
    - '.github/renovate/*.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: ppat/github-workflows/.github/workflows/renovate.yaml@cb285d6ad5b04e96daba7a39cce99d1235415523 # v1.1.1
    with:
      dry_run: "${{ github.event_name	== 'pull_request' }}"
      git_ref: ${{ github.head_ref || github.ref }}
      log_level: debug
      repository: ${{ github.repository }}
    secrets:
      renovate_app_id: ${{ secrets.RENOVATE_APP_ID }}
      renovate_app_private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
